apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fe-test
  name: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fe-test
  template:
    metadata:
      labels:
        app: fe-test
    spec:
      containers:
      - name: main
        image: europe-north1-docker.pkg.dev/code-test-stockholm/code-test/person-family:latest
	imagePullPolicy: Always
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1024m"
          limits:
            memory: "1024Mi"
            cpu: "1024m"